version: "3.4"
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  renovate:
    image: renovate/renovate:slim
    volumes:
      - ./config/renovate:/usr/src/app
    ports:
      - 8080:80
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
