version: "3.4"
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  renovate:
    image: renovate/renovate
    volumes:
      - ./config/renovate:usr/src/app
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
